CREATE TABLE txns (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  txn_type VARCHAR(15) NOT NULL,
  signature VARCHAR(200) NOT NULL,
  priority_fee INT UNSIGNED DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
)
