CREATE TABLE txns (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type ENUM('mine', 'claim'),
  signature VARCHAR(200) NOT NULL,
  priority_fee INT UNSIGNED DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
