CREATE TABLE stake_accounts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pool_id INT NOT NULL,
  mint_pubkey VARCHAR(44) NOT NULL,
  staker_pubkey VARCHAR(44) NOT NULL,
  stake_pda VARCHAR(44) NOT NULL,
  rewards_balance BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  staked_balance BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  total_rewards_earned BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
)
