CREATE TABLE challenges (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pool_id INT NOT NULL,
  submission_id INT,
  challenge BINARY(32) NOT NULL,
  rewards_earned BIGINT UNSIGNED DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
)
