CREATE TABLE miners (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pubkey VARCHAR(44) NOT NULL,
  enabled BOOL DEFAULT false NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
)
